#ifndef __BITS_H__
#define __BITS_H__

/* define for all the bits in a word */

///* 0-1 */
//#define COMB_SHIFT (0)
//#define COMB_MASK (0x0003 << COMB_SHIFT)
///* 2-4 */
//#define DESTINATION_REGISTER_SHIFT (2)
//#define DESTINATION_REGISTER_MASK (0x0007 << DESTINATION_REGISTER_SHIFT)
///* 5-6 */
//#define DESTINATION_ADDRESSING_METHOD_SHIFT (5)
//#define DESTINATION_ADDRESSING_METHOD_MASK (0x0003 << DESTINATION_ADDRESSING_METHOD_SHIFT)
///* 7-9 */
//#define SOURCE_REGISTER_SHIFT (7)
//#define SOURCE_REGISTER_MASK (0x0007 << SOURCE_REGISTER_SHIFT)
///* 10-11 */
//#define SOURCE_ADDRESSING_METHOD_SHIFT (10)
//#define SOURCE_ADDRESSING_METHOD_MASK (0x0003 << SOURCE_ADDRESSING_METHOD_SHIFT)
///* 12-15 */
//#define OPCODE_SHIFT (12)
//#define OPCODE_MASK (0x000F << OPCODE_SHIFT)
///* 16 */
//#define TYPE_SHIFT (16)
//#define TYPE_MASK (0x0001 << TYPE_SHIFT)
///* 17 */
//#define DBL_SHIFT (17)
//#define DBL_MASK (0x0001 << DBL_SHIFT)

/* 0-1 */
#define TYPE_SHIFT (0)
#define TYPE_MASK (0x0003 << TYPE_SHIFT)
/* 2-3 */
#define DESTINATION_ADDRESSING_METHOD_SHIFT (2)
#define DESTINATION_ADDRESSING_METHOD_MASK (0x0003 << DESTINATION_ADDRESSING_METHOD_SHIFT)
/* 2-7 address*/
#define ADDRESS_SHIFT (2)
#define ADDRESS_MASK (0x00FF << ADDRESS_SHIFT)
/* 4-5 */
#define SOURCE_ADDRESSING_METHOD_SHIFT (4)
#define SOURCE_ADDRESSING_METHOD_MASK (0x0003 << SOURCE_ADDRESSING_METHOD_SHIFT)
/* 6-7 */
#define OPCODE_SHIFT (6)
#define OPCODE_MASK (0x000F << OPCODE_SHIFT)

#endif /* __BITS__ */
